export { default as Navigation } from './Navigation';
export { default as GalleryWrapper } from './GalleryWrapper';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as InstagramFeed } from './InstagramFeed';
export { default as Featured } from './Featured';
export { default as Testimonials } from './Testimonials';